# Generated by Django 5.1.1 on 2025-04-01 04:25

import userauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(upload_to=userauth.models.pdf_report_upload_path)),
                ('final_depression', models.FloatField()),
                ('final_anxiety', models.FloatField()),
                ('final_stress', models.FloatField()),
                ('questionnaire_depression', models.FloatField()),
                ('questionnaire_anxiety', models.FloatField()),
                ('questionnaire_stress', models.FloatField()),
                ('audio_depression', models.FloatField()),
                ('audio_anxiety', models.FloatField()),
                ('audio_stress', models.FloatField()),
                ('video_depression', models.FloatField()),
                ('video_anxiety', models.FloatField()),
                ('video_stress', models.FloatField()),
            ],
            options={
                'db_table': 'pdf_report',
                'unique_together': {('email', 'time_stamp')},
            },
        ),
    ]
