export const media = {
  Neutral: [
    {
      id: 1,
      src: 'https://t3.ftcdn.net/jpg/00/65/39/74/360_F_65397486_1brvJ9KipdByBoFpNOLpIJxFdwSigXIY.jpg',
      type: 'image',
      description: 'Plain Landscape',
      question: 'Does this calm or bore you?',
      options: ['Calm', 'Bore'],
    },
    {
      id: 3,
      src: 'https://images.pexels.com/photos/5669338/pexels-photo-5669338.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      type: 'image',
      description: 'Calm Lake',
      question: 'Would you like to sit here and reflect?',
      options: ['Yes', 'No'],
    },
  ],

  Happy: [
    {
      id: 5,
      src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDLqNtZw0QdFpXxJJbgM_iwygQ3DHVJNEEUQ&s',
      type: 'image',
      description: 'Cute Puppy',
      question: 'Does this puppy bring a smile to your face?',
      options: ['Yes', 'No'],
    },
    {
      id: 7,
      src: 'https://img.freepik.com/premium-photo/two-indian-school-friends-smiling-together-school_130568-366.jpg',
      type: 'image',
      description: 'Smiling Friends',
      question: 'Do you miss your childhood friends?',
      options: ['Yes', 'No'],
    },
    {
      id: 8,
      src: 'https://media.istockphoto.com/id/1700386148/video/child-tickling-sibling-on-the-beach-on-the-feet-with-feather-kid-cover-in-sand-smiling.mp4?s=mp4-640x640-is&k=20&c=CUoherEQ9uJwpiCsL-tQaneursQCNVWjIFfU-Q5YPUA=',
      type: 'video',
      description: 'Happy Kids Playing',
      question: 'When was the last time you laughed this hard?',
      options: ['Today', 'This week', 'Last month', 'I can’t remember'],
    },
    {
      id: 6,
      src: 'https://as1.ftcdn.net/jpg/05/60/97/22/1000_F_560972268_gJBiEbWjLl9EDf8BVjvgCuFisz02KTZM.jpg',
      type: 'image',
      description: 'Family Laughing',
      question: 'Do you enjoy spending time with family?',
      options: ['Agree', 'Disagree'],
    },
  ],

  Sad: [
    {
      id: 9,
      src: 'https://dy7glz37jgl0b.cloudfront.net/advice/images/122b354d5e0dd05b511b34a2a19ed840-black-woman-gazing-out-window-couch_l.jpeg',
      type: 'image',
      description: 'Lonely Person',
      question: 'Have you ever felt this lonely?',
      options: ['Yes', 'No'],
    },
    {
      id: 11,
      src: 'https://media.istockphoto.com/id/924201818/video/upset-male-child-suffering-from-parent-quarrels-depression-domestic-violence.mp4?s=mp4-640x640-is&k=20&c=wL043c-nuer1rRoTX4M-8yDTEdC_3rWw5WCf2bXwtmE=',
      type: 'video',
      description: 'Parents fighting',
      question: 'Do conflicts at home affect your mood?',
      options: ['Yes', 'No'],
    },
    {
      id: 12,
      src: 'https://media.istockphoto.com/id/1993516553/video/one-male-person-covering-face-in-shame-sitting-at-home-floor-in-the-dark-during-crisis-person.mp4?s=mp4-640x640-is&k=20&c=wGkQ_IBGkpWb4T88hfIHRgrwTtDrvdOBKcyRmolL-cE=',
      type: 'video',
      description: 'Sad Woman Sitting Alone',
      question: 'Have you ever felt overwhelmed like this?',
      options: ['Yes', 'No'],
    },
  ],

  Anger: [
    {
      id: 17,
      src: 'https://www.shutterstock.com/shutterstock/videos/3719371745/thumb/11.jpg?ip=x480',
      type: 'image',
      description: 'Fight against friends',
      question: 'Have you ever argued with a close friend?',
      options: ['Yes', 'No'],
    },
    {
      id: 19,
      src: 'https://thumbs.dreamstime.com/b/teacher-scolding-student-girl-rampage-angry-blame-her-92396982.jpg',
      type: 'image',
      description: 'Angry Student at Teacher',
      question: 'Have you ever felt misunderstood by a teacher?',
      options: ['Yes', 'No'],
    },
    {
      id: 18,
      src: 'https://media.istockphoto.com/id/1191132580/photo/frustrated-millennial-female-worker-felling-tired-of-working-quarreling.jpg?s=612x612&w=0&k=20&c=Y6oaOPB7WaGe3WlwCrChzGKndU3dGPvzouUrO1N265I=',
      type: 'image',
      description: 'Conflict Scene',
      question: 'How do you handle conflict at work or school?',
      options: ['Talk it out', 'Avoid it', 'Get angry', 'Seek help'],
    },
    {
      id: 20,
      src: 'https://www.shutterstock.com/shutterstock/videos/1055967437/preview/stock-footage-a-frustrated-angry-dominating-male-boss-businessman-shouting-at-an-office-corporate-female.webm',
      type: 'video',
      description: 'Angry Boss on Employee',
      question: 'Have you been yelled at in public?',
      options: ['Yes', 'No'],
    },
  ],

  Fear: [
    {
      id: 13,
      src: 'https://static.vecteezy.com/system/resources/thumbnails/049/532/277/large/devil-vampire-portrait-free-video.jpg',
      type: 'image',
      description: 'Dark Forest',
      question: 'Does darkness scare you?',
      options: ['Yes', 'No'],
    },
    {
      id: 14,
      src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSN4kh3hFtcagyMNyNWsSKGmYMj4ekI4aPUVA&s',
      type: 'image',
      description: 'Shadowy Figure',
      question: 'Have you ever felt someone was watching you?',
      options: ['Yes', 'No'],
    },
    {
      id: 16,
      src: 'https://www.lifeofpretty.com/wp-content/uploads/2021/11/Picture3-2.jpg',
      type: 'image',
      description: 'Scary Shadow Moving',
      question: 'Does this video make you uncomfortable?',
      options: ['Agree', 'Disagree'],
    },
  ],
};
